#!/bin/sh

# 单网口旁路由（Orange Pi Zero）静态IP
uci -q batch << EOT
set network.lan.proto='static'
set network.lan.ipaddr='192.168.0.222'
set network.lan.netmask='255.255.255.0'
set network.lan.gateway='192.168.0.1'
set network.lan.dns='192.168.0.1'
commit network
EOT

# ==================== 单网口必关 IPv6（OpenClash 强烈建议） ====================
uci -q batch << EOT
set network.lan.ipv6=0
set network.globals.ula_prefix=''
set dhcp.lan.dhcpv6=disabled
set dhcp.lan.ra=disabled
set dhcp.lan.ndp=disabled
commit network
commit dhcp
EOT

# 主机名
uci set system.@system[0].hostname='OPi-Zero'
uci commit system

# ==================== 旁路由必需 ====================
# 关闭 DHCP（避免和主路由冲突）
uci set dhcp.lan.ignore=1
uci commit dhcp

# 防火墙转发全开
uci set firewall.@defaults[0].forward=ACCEPT
uci set firewall.@defaults[0].input=ACCEPT
uci set firewall.@defaults[0].output=ACCEPT
uci commit firewall
# =====================================================

# 重启服务
/etc/init.d/network restart
/etc/init.d/firewall restart
/etc/init.d/dnsmasq restart

exit 0